// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_g7EkIlVm7tGMwW2sa1OI7swp02WbdC0',
    appId: '1:680321999109:web:2755d7f7a452e292b4576c',
    messagingSenderId: '680321999109',
    projectId: 'cartie-b84dd',
    authDomain: 'cartie-b84dd.firebaseapp.com',
    storageBucket: 'cartie-b84dd.firebasestorage.app',
    measurementId: 'G-P3PJGF3L7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSTu_WFLG8T9Oc4cpRucEvkizzarzevc',
    appId: '1:680321999109:android:bff82992d86cb8ebb4576c',
    messagingSenderId: '680321999109',
    projectId: 'cartie-b84dd',
    storageBucket: 'cartie-b84dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByeL4973jLw5-DqyPtVl79I3eDN4uAuAQ',
    appId: '1:680321999109:ios:b9dd161f61b80729b4576c',
    messagingSenderId: '680321999109',
    projectId: 'cartie-b84dd',
    storageBucket: 'cartie-b84dd.firebasestorage.app',
    iosBundleId: 'com.ionicinvestments.cartiecartsafe1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByeL4973jLw5-DqyPtVl79I3eDN4uAuAQ',
    appId: '1:680321999109:ios:b4781dfaadda8fc1b4576c',
    messagingSenderId: '680321999109',
    projectId: 'cartie-b84dd',
    storageBucket: 'cartie-b84dd.firebasestorage.app',
    iosBundleId: 'com.ionicinvestments.cartiecartsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_g7EkIlVm7tGMwW2sa1OI7swp02WbdC0',
    appId: '1:680321999109:web:5bd9a4beb54e3c2eb4576c',
    messagingSenderId: '680321999109',
    projectId: 'cartie-b84dd',
    authDomain: 'cartie-b84dd.firebaseapp.com',
    storageBucket: 'cartie-b84dd.firebasestorage.app',
    measurementId: 'G-BC8S788FRV',
  );
}
